sudo: required
os:
  - linux
services:
  - docker
language: go

jobs:
  include:
    - stage: build
      script: make build
    - stage: test
      script: make check
    - stage: deploy
      script: make deploy
      if: tag =~ ^v\d
